from pathlib import Path
p=Path('js/app.js')
s=p.read_text()
old='''function hideAllViews() {\n  Object.values(views).forEach((view) => { if (view) view.hidden = true; });\n}\n\nfunction switchPortalView(view) {\n  navItems.forEach((item) => item.classList.toggle("active", item.dataset.view === view));\n  hideAllViews();\n\n  if (view === "overview") {\n    views.overview.hidden = false;\n    viewTitle.textContent = "Governance Overview";\n    return;\n  }\n  if (view === "documents") {\n    views.documents.hidden = false;\n    viewTitle.textContent = "Board Documents";\n    loadDocuments().catch(console.error);\n    return;\n  }\n  if (view === "directors") {\n    if (!hasPermission(currentProfile, PERMISSIONS.DIRECTORS_VIEW)) return switchPortalView("overview");\n    views.directors.hidden = false;\n    viewTitle.textContent = "Board Directory";\n    loadDirectory().catch(console.error);\n    return;\n  }\n  if (view === "founder") {\n    if (!isFounder(currentProfile)) return switchPortalView("overview");\n    views.founder.hidden = false;\n    viewTitle.textContent = "Founder Director Control";\n    loadFounderWorkspace().catch(console.error);\n    return;\n  }\n\n  views.placeholder.hidden = false;\n  const [title, copy] = moduleCopy[view] || ["Board Module", "This module is not available yet."];\n  viewTitle.textContent = title;\n  placeholderTitle.textContent = title;\n  placeholderCopy.textContent = copy;\n}\n'''
new='''function hideAllViews() {\n  // Dynamic Phase 5-10 sections are created after app.js starts, so the router\n  // must hide every portal section rather than only the original static map.\n  document.querySelectorAll(".portal-section").forEach((section) => { section.hidden = true; });\n}\n\nfunction switchPortalView(view) {\n  document.querySelectorAll(".nav-item[data-view]").forEach((item) => item.classList.toggle("active", item.dataset.view === view));\n  hideAllViews();\n\n  if (view === "overview") {\n    views.overview.hidden = false;\n    viewTitle.textContent = "Governance Overview";\n    return;\n  }\n  if (view === "documents") {\n    views.documents.hidden = false;\n    viewTitle.textContent = "Board Documents";\n    loadDocuments().catch(console.error);\n    return;\n  }\n  if (view === "directors") {\n    if (!hasPermission(currentProfile, PERMISSIONS.DIRECTORS_VIEW)) return switchPortalView("overview");\n    views.directors.hidden = false;\n    viewTitle.textContent = "Board Directory";\n    loadDirectory().catch(console.error);\n    return;\n  }\n  if (view === "founder") {\n    if (!isFounder(currentProfile)) return switchPortalView("overview");\n    views.founder.hidden = false;\n    viewTitle.textContent = "Founder Director Control";\n    loadFounderWorkspace().catch(console.error);\n    return;\n  }\n\n  const dynamicView = document.getElementById(`view-${view}`);\n  if (dynamicView && dynamicView !== views.placeholder) {\n    dynamicView.hidden = false;\n    const titles = {\n      meetings: "Meetings",\n      resolutions: "Resolution Registry",\n      records: "Board Records",\n      governance: "Governance",\n      security: "Security & Audit",\n      launch: "Launch Readiness"\n    };\n    viewTitle.textContent = titles[view] || "Board Governance";\n    window.dispatchEvent(new CustomEvent("tpp:view-changed", { detail: { view } }));\n    return;\n  }\n\n  // Genuine fallback only when a requested module failed to create its view.\n  views.placeholder.hidden = false;\n  const [title] = moduleCopy[view] || ["Board Module"];\n  viewTitle.textContent = title;\n  placeholderTitle.textContent = `${title} unavailable`;\n  placeholderCopy.textContent = "This module did not finish loading. Refresh the portal or check the browser console for the module error.";\n}\n'''
if old not in s:
    raise SystemExit('router anchor not found')
s=s.replace(old,new,1)
p.write_text(s)
